// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnRYeU-zUEjytVFMnXU2PfB24X4WkWh9g',
    appId: '1:1058596184283:web:4ac194e780f6ad09c2ecfe',
    messagingSenderId: '1058596184283',
    projectId: 'fruits-hub-900d2',
    authDomain: 'fruits-hub-900d2.firebaseapp.com',
    storageBucket: 'fruits-hub-900d2.firebasestorage.app',
    measurementId: 'G-P8LMWNK3TB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzymhw-SKxB1B2opMLgVHX4XET85YdTRY',
    appId: '1:1058596184283:android:b5dc6619fa533896c2ecfe',
    messagingSenderId: '1058596184283',
    projectId: 'fruits-hub-900d2',
    storageBucket: 'fruits-hub-900d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhLIWfFBW3nh7K2RidWY9ZLg8_jrH2tOk',
    appId: '1:1058596184283:ios:3e036d56ec24bb1bc2ecfe',
    messagingSenderId: '1058596184283',
    projectId: 'fruits-hub-900d2',
    storageBucket: 'fruits-hub-900d2.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhLIWfFBW3nh7K2RidWY9ZLg8_jrH2tOk',
    appId: '1:1058596184283:ios:3e036d56ec24bb1bc2ecfe',
    messagingSenderId: '1058596184283',
    projectId: 'fruits-hub-900d2',
    storageBucket: 'fruits-hub-900d2.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnRYeU-zUEjytVFMnXU2PfB24X4WkWh9g',
    appId: '1:1058596184283:web:27362b7ca31b9225c2ecfe',
    messagingSenderId: '1058596184283',
    projectId: 'fruits-hub-900d2',
    authDomain: 'fruits-hub-900d2.firebaseapp.com',
    storageBucket: 'fruits-hub-900d2.firebasestorage.app',
    measurementId: 'G-SY0TLL4BDS',
  );
}
